# Generated by Django 4.2.3 on 2023-07-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.URLField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.everestkitchenpa.com%2Fmenu.html&psig=AOvVaw2i2EdiX2f0G0E7JDy4Zd-N&ust=1690722099545000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCID96uP8s4ADFQAAAAAdAAAAABAK'),
        ),
    ]
