# Generated by Django 4.2.3 on 2023-07-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.URLField(default='https://dha.cafeela.pk/wp-content/uploads/woocommerce-placeholder-433x237.png', max_length=500),
        ),
    ]
