# Generated by Django 4.2.4 on 2023-08-08 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_item_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Items'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='user_name',
        ),
    ]
