# Generated by Django 4.2.4 on 2023-08-08 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_alter_item_options_remove_item_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
    ]
