# Generated by Django 4.2.4 on 2023-08-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_remove_item_item_description_item_item_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_desc',
        ),
        migrations.RemoveField(
            model_name='item',
            name='user_name',
        ),
        migrations.AddField(
            model_name='item',
            name='item_description',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.URLField(default='https://dha.cafeela.pk/wp-content/uploads/woocommerce-placeholder-433x237.png', max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
    ]
